set(MDI_DIR "${mdi_SOURCE_DIR}/svg")

qt_add_resources(${PROJECT_NAME}_app "logos"
	PREFIX "/logos"
	BASE "res"
	FILES
	"res/caw.svg"
)

qt_add_resources(${PROJECT_NAME}_app "mdi"
	PREFIX "/mdi"
	BASE "${MDI_DIR}"
	FILES
	"${MDI_DIR}/bug.svg"
	"${MDI_DIR}/chevron-double-down.svg"
	"${MDI_DIR}/chevron-down.svg"
	"${MDI_DIR}/chevron-up.svg"
	"${MDI_DIR}/cog.svg"
	"${MDI_DIR}/content-duplicate.svg"
	"${MDI_DIR}/content-save.svg"
	"${MDI_DIR}/delete.svg"
	"${MDI_DIR}/export.svg"
	"${MDI_DIR}/file-plus.svg"
	"${MDI_DIR}/folder-open.svg"
	"${MDI_DIR}/link-off.svg"
	"${MDI_DIR}/link.svg"
	"${MDI_DIR}/minus.svg"
	"${MDI_DIR}/play.svg"
	"${MDI_DIR}/plus.svg"
	"${MDI_DIR}/record.svg"
	"${MDI_DIR}/repeat.svg"
	"${MDI_DIR}/sawtooth-wave.svg"
	"${MDI_DIR}/sine-wave.svg"
	"${MDI_DIR}/square-wave.svg"
	"${MDI_DIR}/step-forward.svg"
	"${MDI_DIR}/triangle-wave.svg"
)

qt_add_resources(${PROJECT_NAME}_app "presets"
	PREFIX "/presets"
	BASE "presets"
	FILES
	"presets/base_string.json"
	"presets/bass_drum_1.json"
	"presets/bass_drum_2.json"
	"presets/bass_drum_3.json"
	"presets/bell.json"
	"presets/classic_8bit.json"
	"presets/default.json"
	"presets/hihat_1.json"
	"presets/hihat_2.json"
	"presets/pipe_hit.json"
	"presets/smash.json"
	"presets/snare_1.json"
	"presets/snare_2.json"
	"presets/softy.json"
	"presets/square.json"
	"presets/wind.json"
)

qt_add_resources(${PROJECT_NAME}_app "dark_theme"
	PREFIX "/themes/dark"
	BASE "res/themes/dark"
	FILES
	"res/themes/dark/applicationwindow-background.png"
	"res/themes/dark/applicationwindow-overlay.png"
	"res/themes/dark/applicationwindow-overlay-modal.png"
	"res/themes/dark/busyindicator-animation.webp"
	"res/themes/dark/button-background.9.png"
	"res/themes/dark/menu-background.9.png"
	"res/themes/dark/menuitem-background.9.png"
	"res/themes/dark/menuitem-background-highlighted.9.png"
)